//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class OrdenEnvio
{
    public int IdOE { get; set; }
    public int VentaOE { get; set; }
    public int ClienteOE { get; set; }
    public long CadeteOE { get; set; }
    public string UbicacionOE { get; set; }
    public DateTime FechaOE { get; set; }
    public string EstadoOE { get; set; }
    public List<ProductosOE> ProductosOrdenEnvio { get; set; }
    public string LocalidadOE { get; set; }
    public int CantidadProductos { get{return ProductosOrdenEnvio.Count; } }


    public OrdenEnvio(int idOE, int ventaOE, int clienteoe, long cadeteoe, string ubicacionOE, DateTime fechaOE, string estadoOE, List<ProductosOE> productosOrdenEnvio, string departamento)
    {
        IdOE = idOE;
        VentaOE = ventaOE;
        ClienteOE = clienteoe;
        CadeteOE = cadeteoe;
        UbicacionOE = ubicacionOE;
        FechaOE = fechaOE;
        EstadoOE = estadoOE;
        ProductosOrdenEnvio = productosOrdenEnvio;
        LocalidadOE = departamento;
    }

    public OrdenEnvio()
    {
    }
    
}
